### ISSUE TITLE
Segmentation Fault on Kali Linux

### ISSUE THREAD

**Issue by Cryptiiiic** [tihmstar/partialZipBrowser#1]
The program runs fine when i just run pzb but if i do -l or --list, then i get the seg fault.

pzb -l https://example.com/whatever.zip

Then I get: Segmentation fault (core dumped)

And when I run it in gdb, i get.

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.

**Comment by tihmstar** [comment]
Since you already loaded it into gdb more information like backtrace, registers, etc would be helpful
