### ISSUE TITLE
-o parameter doesn't seem to work

### ISSUE THREAD

**Issue by arx8x** [tihmstar/partialZipBrowser#3]
files are downloaded to current dir

**Comment by ghost** [comment]
i want to build the partial zip browser

**Comment by arx8x** [comment]
http://api.tihmstar.net/builds/partialZipBrowser/partialZipBrowser-latest.zip

**Comment by ghost** [comment]
How to compile pzb downloaded from github not from tihmstar

**Comment by ghost** [comment]
how to compile the pzb from github

**Comment by ghost** [comment]
how to compile the pzb from github
