### ISSUE TITLE
Wrong file size when try to get SEP file on iOS 11.3b1-b4 

### ISSUE THREAD

**Issue by jihyo-song** [tihmstar/partialZipBrowser#5]
Don't know what's wrong, but when I try to download / get SEP file from 11.3b1-b4, it downloaded but the size only 396 bytes instead about 2mb+. 

on the other side, Baseband and BuildManifest.plist from 11.3b1-b4 it seems perfectly fine, file size are correct. and When I try to download / get SEP file from 11.2.6, it perfectly fine.

I'm using latest commit partialZipBrowser.

Any idea ? Thank you!

**Comment by goodboydheeraj** [comment]
Yes, same issue for me. please look into this

**Comment by tihmstar** [comment]
Please provide more information and instructions to reprocude the issue

**Comment by jihyo-song** [comment]
https://drive.google.com/open?id=1M8cHKBvO2HhJpLHzRTuYNFEYfAtjN0hk

This issues only happens when i want to grab the SEP file on iOS 11.3 later, on the other side there's no issue when i want to grab Baseband and Manifest file on iOS 11.3 later. Hopefully you can understand what i mean. Sorry i can't explained perfectly, English is not my native language. Thank you.

Edit: 
Even on the latest commit 31 pzb, this issues still happen.

**Comment by tihmstar** [comment]
I remember seeing this bug which should have been fixed in https://github.com/tihmstar/libfragmentzip/commit/a52e0770dafc6ef3a420042b7342cf1e971a9a0b
Can you re-check if you see the same behavior of downloading the wrong file with the latest version of partialZipBrowser *and* libfragmentzip ?

**Comment by jihyo-song** [comment]
https://imgur.com/a/xNGIHtJ

It show **cannot find input file: `Makefile.in'** when I tried to compile the latest commit partialZipBrowser. For libfragmentzip it's perfectly fine, installed correctly (because no show error about libfragmentzip >-42 when compiling the latest commit partialZipBrowser). 

Any idea ? Or did I miss some step ? Thank you.

**Comment by tihmstar** [comment]
Looks like your version of libfragmentzip is wrong. 
you definetly need to get the latest libfragmentzip before trying to build pzb.

**Comment by jihyo-song** [comment]
Sorry for late reply ... 

Oh man it finally fixed by using pzb commit 31 + libfragmentzip commit 42, pzb now downloaded the SEP file correctly. Don't know why I can't compile the pzb commit 32 on my Mac, but on pzb commit 31 it perfectly fine. So this problem happens because of libfragmentzip bug tho ?

Thank you so much!
