### ISSUE TITLE
Can’t allocate region

### ISSUE THREAD

**Issue by MCApollo** [tihmstar/partialZipBrowser#7]
pzb http://updates-http.cdn-apple.com/2018FallFCS/fullrestores/091-63220/11676EA8-AC8E-11E8-B3C7-D85EDF907439/iPhone_5.5_12.0_16A366_Restore.ipsw
init pzb: http://updates-http.cdn-apple.com/2018FallFCS/fullrestores/091-63220/11676EA8-AC8E-11E8-B3C7-D85EDF907439/iPhone_5.5_12.0_16A366_Restore.ipsw
init done
 $ ls
     20813 f BuildManifest.plist
         0 d Firmware/
       475 f Restore.plist
  13265766 f kernelcache.release.iphone7
  14345079 f kernelcache.release.n66
  53289639 f 048-08497-242.dmg
  53984312 f 048-08422-242.dmg
3060565099 f 048-08888-230.dmg
 $ get 048-08888-230.dmg 
getting: 048-08888-230.dmg
  0% [                                                              100% [===================================================================================================>]
pzb(26661,0x1b4b02b40) malloc: *** mach_vm_map(size=3060580352) failed (error code=3)
*** error: can't allocate region
  0% [                                                                                                    ]
download failed
 $ 

Darwin MC 17.5.0 Darwin Kernel Version 17.5.0: Tue Mar 13 21:32:11 PDT 2018; root:xnu-4570.52.2~8/RELEASE_ARM64_S8000 iPhone8,2 arm64 N66mAP Darwin

**Comment by MCApollo** [comment]
More info: 
Cross compiled using the 9.0 SDK for arm64, used on electra.

Thank you for using autoconf, it makes cross compiling easier.

**Comment by tihmstar** [comment]
From first sight this looks like a memory issue. 
When lfz downloads a file it is fully stored in RAM before it is unpacked and written to disk. 
It looks like you're trying to download the main filesystem from the ipsw, which is pretty huge. 
On iPhones there is a certain limit how much memory can be allocated at once, especially a limit on how much one single application can allocate.
By downloading the file you need to allocate the compressed file size, as well as a buffer large enough to hold the uncompressed data. 
Which should be around 5GB for the main filesystem inside the ipsw. 

One possible way of working around these restrictions is to first fully download the compressed file and then uncompress it from disk, however this is kinda not what lzf was made for in first place, so i'm not even sure about *fixing* this.

The idea of libfragmentzip is that you are able to download a single tiny file from a huge remote zipfile, without having to download the entire file. Which is in our case pretty much every file but the main filesystem. 
So if you want to get the main fs, i feel like just downloading the entire zip/ipsw would be way easier. 

with ```unzip``` it is even possible to extract one single file from a local zip.

**Comment by MCApollo** [comment]
I knew it was a memory issue, I just was wondering your thoughts on support for big files.

Even though my use case is a *very* special one, this problem could bleed into other systems. I was wondering if this could be a solution to downloading WiFi firmware files the legal way without downloading the whole IPSW.

Why would not writing to disk *while* downloading (not holding the whole thing in RAM) or downloading a file in chunks not be a viable option?

Oh while I’m commenting, I recommend when someone sends a EOF (^D) to the interactive CLI the program gets terminated.

**Comment by tihmstar** [comment]
What is the benefit of just downloading the main filesystem without the other files, when you might aswell just get the full ipsw?
Like all the other files are less than 5% of the main fs, so downloading them too doesn't impact performance at all

**Comment by MCApollo** [comment]
I wanna say you’re right, but I’m showing my side of my argument before exploring other options.

**I’m making a script that does this:**
Download IPSW —> Extarct FS (dmg) —> Remove IPSW —> Extract FS (dmg) —> Grab files —> Remove FS (dmg)

Like the afc2 released by angelxwind, I need to grab files the legal way, but her version only downloads the 7.0 OTA update (only needing to download certain bytes)- I want my tool to age well and not have to push updates when new iOS releases, but I cannot find a good solution for this.

Mind you, this script is targeting jailbroken iOS devices- My limitations are space on device, cpu,  and memory. Cutting the IPSW and downloading the FS (.dmg) would be a **major** improvement. If you add support for large files, I would be able to cut the cpu usage (Not having to extract the IPSW for the FS) and I would be able to save storage space (5% of a 3GB IPSW would be 300MB- something useful when you’re on a memory-tight device). Yes *downloading* all the files doesn’t impact performance, but they become a waste of space. The 5% could be more than 5% and a lot more space could be save rather than asking the user to delete somethings for this script (I’m taking about 16/32GB devices).

I’m closing the issue now, thank you for responding.
